[project]
name = "dobby-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.75.0",
    "logfire>=4.16.0",
    "loguru>=0.7.3",
    "openai>=2.14.0",
    "pydantic>=2.12.5",
]
